services:

    app.service.thirdparty.s3ClientProvider:
        class: AppBundle\Service\ThirdParty\S3ClientProvider
        arguments: ['%s3_region%', '%s3_secret%', '%s3_key%']

    app.service.thirdparty.s3manager:
        class: AppBunlde\Service\ThirdParty\S3Manager